"""Sandbox billing system — fake money, real metrics.

Tracks every token spent (input and output) and computes
what it WOULD cost on Claude, GPT-4, and other APIs.
Lets you compare Forge's local efficiency against cloud
APIs dollar-for-dollar.

The sandbox wallet starts with $50.00. You can /topup any
time. All costs are tracked per-session and per-lifetime.
"""

import json
import os
import tempfile
import time
import logging
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

# Pricing per 1M tokens (as of Feb 2026)
# These are the numbers that cloud AI companies charge
PRICING = {
    "claude_opus_input": 15.00,     # $15/M input tokens
    "claude_opus_output": 75.00,    # $75/M output tokens
    "claude_sonnet_input": 3.00,    # $3/M input tokens
    "claude_sonnet_output": 15.00,  # $15/M output tokens
    "gpt4o_input": 2.50,            # $2.50/M input tokens
    "gpt4o_output": 10.00,          # $10/M output tokens
    "forge_input": 0.00,            # $0 — it's YOUR GPU
    "forge_output": 0.00,           # $0 — it's YOUR GPU
}

DEFAULT_BALANCE = 50.00  # Starting sandbox balance


class BillingMeter:
    """Tracks token usage and computes comparative costs."""

    def __init__(self, persist_path: Optional[Path] = None,
                 starting_balance: float = DEFAULT_BALANCE):
        self._persist_path = persist_path
        self.balance = starting_balance
        self.starting_balance = starting_balance

        # Session counters
        self.session_input_tokens = 0
        self.session_output_tokens = 0
        self.session_cache_hits = 0      # Tokens NOT spent due to caching
        self.session_tool_tokens = 0     # Tokens spent on tool results
        self.session_start = time.time()

        # Lifetime counters
        self.lifetime_input_tokens = 0
        self.lifetime_output_tokens = 0
        self.lifetime_cache_savings = 0
        self.lifetime_sessions = 0
        self.lifetime_topups = 0.0

        # Per-turn tracking
        self._turns: list[dict] = []

        if persist_path and persist_path.exists():
            self._load()
        self.lifetime_sessions += 1

    def record_turn(self, input_tokens: int, output_tokens: int,
                    cache_hit_tokens: int = 0, tool_tokens: int = 0):
        """Record a single turn's token usage.

        Args:
            input_tokens: Tokens in the prompt (context + user message).
            output_tokens: Tokens generated by the model.
            cache_hit_tokens: Tokens saved by file cache (not sent to model).
            tool_tokens: Tokens from tool results added to context.
        """
        self.session_input_tokens += input_tokens
        self.session_output_tokens += output_tokens
        self.session_cache_hits += cache_hit_tokens
        self.session_tool_tokens += tool_tokens

        self.lifetime_input_tokens += input_tokens
        self.lifetime_output_tokens += output_tokens
        self.lifetime_cache_savings += cache_hit_tokens

        # Deduct from sandbox balance using Claude Opus pricing
        # (the most expensive common model — worst case comparison)
        cost = self._compute_cost(
            input_tokens, output_tokens,
            "claude_opus_input", "claude_opus_output")
        self.balance -= cost

        self._turns.append({
            "time": time.time(),
            "input": input_tokens,
            "output": output_tokens,
            "cache_saved": cache_hit_tokens,
            "cost_opus": cost,
            "balance_after": self.balance,
        })

        if self._persist_path:
            self._save()

    def topup(self, amount: float = DEFAULT_BALANCE):
        """Add funds to sandbox balance."""
        self.balance += amount
        self.lifetime_topups += amount
        if self._persist_path:
            self._save()

    def reset_lifetime(self):
        """Reset all lifetime stats to zero. Current session is preserved."""
        self.lifetime_input_tokens = 0
        self.lifetime_output_tokens = 0
        self.lifetime_cache_savings = 0
        self.lifetime_sessions = 1  # current session counts as 1
        self.lifetime_topups = 0.0
        self.balance = self.starting_balance
        if self._persist_path:
            self._save()

    @staticmethod
    def _compute_cost(input_tokens: int, output_tokens: int,
                      input_price_key: str, output_price_key: str) -> float:
        """Compute cost in dollars.

        Multiplies tokens * price first, then divides by 1M to minimize
        float precision loss on small token counts.
        """
        input_cost = (input_tokens * PRICING[input_price_key]) / 1_000_000
        output_cost = (output_tokens * PRICING[output_price_key]) / 1_000_000
        return input_cost + output_cost

    def get_comparison(self) -> dict:
        """Compare costs across providers for the current session."""
        inp = self.session_input_tokens
        out = self.session_output_tokens
        cached = self.session_cache_hits

        # What Claude would charge (including re-reads Forge cached)
        claude_inp_with_waste = inp + cached  # Claude re-reads everything
        opus_cost = self._compute_cost(
            claude_inp_with_waste, out,
            "claude_opus_input", "claude_opus_output")
        sonnet_cost = self._compute_cost(
            claude_inp_with_waste, out,
            "claude_sonnet_input", "claude_sonnet_output")
        gpt4o_cost = self._compute_cost(
            claude_inp_with_waste, out,
            "gpt4o_input", "gpt4o_output")

        # What Forge actually costs (just electricity)
        forge_cost = 0.0  # It's free, baby

        # What Forge WOULD cost on Claude pricing (without the cache waste)
        forge_on_opus = self._compute_cost(
            inp, out, "claude_opus_input", "claude_opus_output")

        # Per-component costs for display
        opus_in = (claude_inp_with_waste * PRICING["claude_opus_input"]) / 1_000_000
        opus_out = (out * PRICING["claude_opus_output"]) / 1_000_000
        sonnet_in = (claude_inp_with_waste * PRICING["claude_sonnet_input"]) / 1_000_000
        sonnet_out = (out * PRICING["claude_sonnet_output"]) / 1_000_000
        gpt4o_in = (claude_inp_with_waste * PRICING["gpt4o_input"]) / 1_000_000
        gpt4o_out = (out * PRICING["gpt4o_output"]) / 1_000_000
        forge_opus_in = (inp * PRICING["claude_opus_input"]) / 1_000_000
        forge_opus_out = (out * PRICING["claude_opus_output"]) / 1_000_000

        return {
            "session_input_tokens": inp,
            "session_output_tokens": out,
            "session_total_tokens": inp + out,
            "cache_tokens_saved": cached,
            "comparisons": {
                "Claude Opus (with re-reads)": {
                    "cost": opus_cost,
                    "input_cost": opus_in,
                    "output_cost": opus_out,
                    "input_tokens": claude_inp_with_waste,
                },
                "Claude Sonnet (with re-reads)": {
                    "cost": sonnet_cost,
                    "input_cost": sonnet_in,
                    "output_cost": sonnet_out,
                    "input_tokens": claude_inp_with_waste,
                },
                "GPT-4o (with re-reads)": {
                    "cost": gpt4o_cost,
                    "input_cost": gpt4o_in,
                    "output_cost": gpt4o_out,
                    "input_tokens": claude_inp_with_waste,
                },
                "Forge (local)": {
                    "cost": forge_cost,
                    "input_cost": 0.0,
                    "output_cost": 0.0,
                    "input_tokens": inp,
                },
                "Forge tokens on Opus pricing": {
                    "cost": forge_on_opus,
                    "input_cost": forge_opus_in,
                    "output_cost": forge_opus_out,
                    "input_tokens": inp,
                    "note": "What Forge's efficient tokens would cost on Claude",
                },
            },
            "savings_vs_opus": opus_cost - forge_on_opus,
            "savings_from_cache": (cached / 1_000_000) * PRICING["claude_opus_input"],
        }

    def status(self) -> dict:
        """Current billing status for display."""
        elapsed = time.time() - self.session_start
        session_total = self.session_input_tokens + self.session_output_tokens

        return {
            "balance": round(self.balance, 4),
            "session_tokens": session_total,
            "session_input": self.session_input_tokens,
            "session_output": self.session_output_tokens,
            "session_cached": self.session_cache_hits,
            "session_duration_m": round(elapsed / 60, 1),
            "turns": len(self._turns),
            "lifetime_tokens": (self.lifetime_input_tokens
                                + self.lifetime_output_tokens),
            "lifetime_sessions": self.lifetime_sessions,
            "lifetime_cache_savings": self.lifetime_cache_savings,
            "cost_per_turn_avg": (
                (DEFAULT_BALANCE + self.lifetime_topups - self.balance)
                / max(1, len(self._turns))
            ),
        }

    def to_audit_dict(self) -> dict:
        """Return a JSON-serializable audit snapshot.

        Stable API contract for the audit exporter.
        """
        return {
            "schema_version": 1,
            **self.status(),
            "comparisons": self.get_comparison()["comparisons"],
        }

    def _save(self):
        """Persist billing data atomically."""
        try:
            self._persist_path.parent.mkdir(parents=True, exist_ok=True)
            data = {
                "version": 1,
                "balance": self.balance,
                "starting_balance": self.starting_balance,
                "lifetime_input_tokens": self.lifetime_input_tokens,
                "lifetime_output_tokens": self.lifetime_output_tokens,
                "lifetime_cache_savings": self.lifetime_cache_savings,
                "lifetime_sessions": self.lifetime_sessions,
                "lifetime_topups": self.lifetime_topups,
            }
            content = json.dumps(data, indent=2)
            fd, tmp_path = tempfile.mkstemp(
                dir=str(self._persist_path.parent),
                suffix=".tmp", prefix="billing_")
            closed = False
            try:
                os.write(fd, content.encode("utf-8"))
                os.close(fd)
                closed = True
                os.replace(tmp_path, str(self._persist_path))
            except Exception:
                if not closed:
                    os.close(fd)
                Path(tmp_path).unlink(missing_ok=True)
                raise
        except Exception as e:
            log.debug("Billing save failed: %s", e)

    def _load(self):
        """Load persisted billing data."""
        try:
            data = json.loads(
                self._persist_path.read_text(encoding="utf-8"))
            self.balance = data.get("balance", DEFAULT_BALANCE)
            self.starting_balance = data.get("starting_balance", DEFAULT_BALANCE)
            self.lifetime_input_tokens = data.get("lifetime_input_tokens", 0)
            self.lifetime_output_tokens = data.get("lifetime_output_tokens", 0)
            self.lifetime_cache_savings = data.get("lifetime_cache_savings", 0)
            self.lifetime_sessions = data.get("lifetime_sessions", 0)
            self.lifetime_topups = data.get("lifetime_topups", 0.0)
        except Exception as e:
            log.debug("Billing load failed: %s", e)
